/////////////////////////////////////////////////////////////////
// NOTE: This file is autogenerated. Changes should be applied to
// the script generate-buildinfo.sh. Recompile all depending
// make targets afterwards.
/////////////////////////////////////////////////////////////////
#define EXAHYPE_GIT_BRANCH          "master"
#define EXAHYPE_GIT_COMMIT_REVISION "04c0026a45775173c54545a3f233f5f45932a6ae"
#define EXAHYPE_GIT_COMMIT_DATE     "Thu Jul 28 17:06:43 2016 +0200"
#define EXAHYPE_BUILD_DATE          "Thu Jul 28 17:09:00 CEST 2016"
