/////////////////////////////////////////////////////////////////
// NOTE: This file is autogenerated. Changes should be applied to
// the script generate-buildinfo.sh. Recompile all depending
// make targets afterwards.
/////////////////////////////////////////////////////////////////
#define EXAHYPE_GIT_BRANCH          "master"
#define EXAHYPE_GIT_COMMIT_REVISION "a5d53c2c16fd09a6289027f47cbf9f0000389283"
#define EXAHYPE_GIT_COMMIT_DATE     "Author: Sven K <sven@nils.local>"
#define EXAHYPE_BUILD_DATE          "Fri Jul 29 00:40:52 CEST 2016"
