/*
 * ! This file is autogenerated and should not be modified !
 * (This file should be generated according to a config file)
 *
 * PdeInfo.h
 */

#ifndef PDEINFO_H_
#define PDEINFO_H_

#include "peano/utils/Globals.h"

#define NUM_PDE 2

namespace exahype {
static const int numberOfVariables[NUM_PDE] = {
    3,1
};
static const int order[NUM_PDE] = {
    3,3
};
}

#endif /* PDEINFO_H_ */
