#!/bin/bash
# a 2017 version of the ExaHyPE build infos

cd "$(dirname "$0")"
buildinfo="./buildinfo.h"
info() { echo "$@" >> $buildinfo; }

echo "/* This file is autogenerated by generate-buildinfo.sh */" > $buildinfo
info
info "#ifndef _EXAHYPE_BUILD_INFO_H_"
info "#define _EXAHYPE_BUILD_INFO_H_"
info
info "#define EXAHYPE_BUILDINFO_AVAILABLE"
info "#define EXAHYPE_BUILD_DATE          "\"$(LC_ALL=en_US.utf8 date)\"
info "#define EXAHYPE_BUILD_HOST          "\"$(hostname)\"
info
info "/* Strings passed by the Makefile */"
info "#define EXAHYPE_BUILD_INFO \\"
for assignment in "$@"; do info "    \"$assignment\\n\" \\"; done
info "    \"\""
info

# I don't think these git information is that useful
if false; then
	if which git &>/dev/null; then
		info "/* Information collected with git */"
		git=$(which git)

		GIT_COMMIT_REV=`$git log | head -1`
		GIT_COMMIT_REV=${GIT_COMMIT_REV#commit }
		GIT_COMMIT_DATE=`$git log | head -3 | tail -1`
		GIT_COMMIT_DATE=`echo ${GIT_COMMIT_DATE#Date\: } | xargs`

		info "#define EXAHYPE_GIT_BRANCH          "\"`$git rev-parse --abbrev-ref HEAD`\"
		info "#define EXAHYPE_GIT_COMMIT_REVISION "\"${GIT_COMMIT_REV}\"
		info "#define EXAHYPE_GIT_COMMIT_DATE     "\"${GIT_COMMIT_DATE}\"
	else
		info "/* No git found */"
		info "#define EXAHYPE_GIT_INFO \"No git available\""
	fi
fi


info
info "#endif /* EXAHYPE_BUILD_INFO_H */"
