void gemm_5_4_4_lduh_x(const double* A, const double* B, double* C) {
#ifdef __AVX2__
#ifdef __AVX512F__
#pragma message ("LIBXSMM KERNEL COMPILATION WARNING: compiling AVX2 code on AVX512 or newer architecture: " __FILE__)
#endif
  __asm__ __volatile__("movq %0, %%rsi\n\t"
                       "movq %1, %%rdi\n\t"
                       "movq %2, %%rdx\n\t"
                       "movq $0, %%r12\n\t"
                       "movq $0, %%r13\n\t"
                       "movq $0, %%r14\n\t"
                       "0:\n\t"
                       "addq $3, %%r13\n\t"
                       "movq $0, %%r12\n\t"
                       "1:\n\t"
                       "addq $4, %%r12\n\t"
                       "vmovupd 0(%%rdx), %%ymm13\n\t"
                       "vmovupd 40(%%rdx), %%ymm14\n\t"
                       "vmovupd 80(%%rdx), %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 0(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm13\n\t"
                       "vbroadcastsd 32(%%rsi), %%ymm1\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm14\n\t"
                       "vbroadcastsd 64(%%rsi), %%ymm2\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 8(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm13\n\t"
                       "vbroadcastsd 40(%%rsi), %%ymm1\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm14\n\t"
                       "vbroadcastsd 72(%%rsi), %%ymm2\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 16(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm13\n\t"
                       "vbroadcastsd 48(%%rsi), %%ymm1\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm14\n\t"
                       "vbroadcastsd 80(%%rsi), %%ymm2\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 24(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm13\n\t"
                       "vbroadcastsd 56(%%rsi), %%ymm1\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm14\n\t"
                       "vbroadcastsd 88(%%rsi), %%ymm2\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovupd %%ymm13, 0(%%rdx)\n\t"
                       "vmovupd %%ymm14, 40(%%rdx)\n\t"
                       "vmovupd %%ymm15, 80(%%rdx)\n\t"
                       "addq $32, %%rdx\n\t"
                       "subq $224, %%rdi\n\t"
                       "cmpq $4, %%r12\n\t"
                       "jl 1b\n\t"
                       "1:\n\t"
                       "addq $1, %%r12\n\t"
                       "vmovsd 0(%%rdx), %%xmm13\n\t"
                       "vmovsd 40(%%rdx), %%xmm14\n\t"
                       "vmovsd 80(%%rdx), %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 0(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vmovsd 32(%%rsi), %%xmm1\n\t"
                       "vfmadd231sd %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vmovsd 64(%%rsi), %%xmm2\n\t"
                       "vfmadd231sd %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 8(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vmovsd 40(%%rsi), %%xmm1\n\t"
                       "vfmadd231sd %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vmovsd 72(%%rsi), %%xmm2\n\t"
                       "vfmadd231sd %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 16(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vmovsd 48(%%rsi), %%xmm1\n\t"
                       "vfmadd231sd %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vmovsd 80(%%rsi), %%xmm2\n\t"
                       "vfmadd231sd %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 24(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vmovsd 56(%%rsi), %%xmm1\n\t"
                       "vfmadd231sd %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vmovsd 88(%%rsi), %%xmm2\n\t"
                       "vfmadd231sd %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovsd %%xmm13, 0(%%rdx)\n\t"
                       "vmovsd %%xmm14, 40(%%rdx)\n\t"
                       "vmovsd %%xmm15, 80(%%rdx)\n\t"
                       "addq $8, %%rdx\n\t"
                       "subq $248, %%rdi\n\t"
                       "cmpq $5, %%r12\n\t"
                       "jl 1b\n\t"
                       "addq $80, %%rdx\n\t"
                       "addq $96, %%rsi\n\t"
                       "subq $40, %%rdi\n\t"
                       "cmpq $3, %%r13\n\t"
                       "jl 0b\n\t"
                       "0:\n\t"
                       "addq $1, %%r13\n\t"
                       "movq $0, %%r12\n\t"
                       "1:\n\t"
                       "addq $4, %%r12\n\t"
                       "vmovupd 0(%%rdx), %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 0(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm1, %%ymm0, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 8(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm1, %%ymm0, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 16(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm1, %%ymm0, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 24(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm1, %%ymm0, %%ymm15\n\t"
                       "vmovupd %%ymm15, 0(%%rdx)\n\t"
                       "addq $32, %%rdx\n\t"
                       "subq $224, %%rdi\n\t"
                       "cmpq $4, %%r12\n\t"
                       "jl 1b\n\t"
                       "1:\n\t"
                       "addq $1, %%r12\n\t"
                       "vmovsd 0(%%rdx), %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 0(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 8(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 16(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 24(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovsd %%xmm15, 0(%%rdx)\n\t"
                       "addq $8, %%rdx\n\t"
                       "subq $248, %%rdi\n\t"
                       "cmpq $5, %%r12\n\t"
                       "jl 1b\n\t"
                       "addq $0, %%rdx\n\t"
                       "addq $32, %%rsi\n\t"
                       "subq $40, %%rdi\n\t"
                       "cmpq $4, %%r13\n\t"
                       "jl 0b\n\t"
                       : : "m"(B), "m"(A), "m"(C) : "rdi","rsi","rdx","r12","r13","r14","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15");
#else
#pragma message ("LIBXSMM KERNEL COMPILATION ERROR in: " __FILE__)
#error No kernel was compiled, lacking support for current architecture?
#endif

#ifndef NDEBUG
#ifdef _OPENMP
#pragma omp atomic
#endif
libxsmm_num_total_flops += 160;
#endif
}

void gemm_5_4_4_lduh_y(const double* A, const double* B, double* C) {
#ifdef __AVX2__
#ifdef __AVX512F__
#pragma message ("LIBXSMM KERNEL COMPILATION WARNING: compiling AVX2 code on AVX512 or newer architecture: " __FILE__)
#endif
  __asm__ __volatile__("movq %0, %%rsi\n\t"
                       "movq %1, %%rdi\n\t"
                       "movq %2, %%rdx\n\t"
                       "movq $0, %%r12\n\t"
                       "movq $0, %%r13\n\t"
                       "movq $0, %%r14\n\t"
                       "0:\n\t"
                       "addq $3, %%r13\n\t"
                       "movq $0, %%r12\n\t"
                       "1:\n\t"
                       "addq $4, %%r12\n\t"
                       "vmovupd 0(%%rdx), %%ymm13\n\t"
                       "vmovupd 160(%%rdx), %%ymm14\n\t"
                       "vmovupd 320(%%rdx), %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 0(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm13\n\t"
                       "vbroadcastsd 32(%%rsi), %%ymm1\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm14\n\t"
                       "vbroadcastsd 64(%%rsi), %%ymm2\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 8(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm13\n\t"
                       "vbroadcastsd 40(%%rsi), %%ymm1\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm14\n\t"
                       "vbroadcastsd 72(%%rsi), %%ymm2\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 16(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm13\n\t"
                       "vbroadcastsd 48(%%rsi), %%ymm1\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm14\n\t"
                       "vbroadcastsd 80(%%rsi), %%ymm2\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 24(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm13\n\t"
                       "vbroadcastsd 56(%%rsi), %%ymm1\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm14\n\t"
                       "vbroadcastsd 88(%%rsi), %%ymm2\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovupd %%ymm13, 0(%%rdx)\n\t"
                       "vmovupd %%ymm14, 160(%%rdx)\n\t"
                       "vmovupd %%ymm15, 320(%%rdx)\n\t"
                       "addq $32, %%rdx\n\t"
                       "subq $224, %%rdi\n\t"
                       "cmpq $4, %%r12\n\t"
                       "jl 1b\n\t"
                       "1:\n\t"
                       "addq $1, %%r12\n\t"
                       "vmovsd 0(%%rdx), %%xmm13\n\t"
                       "vmovsd 160(%%rdx), %%xmm14\n\t"
                       "vmovsd 320(%%rdx), %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 0(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vmovsd 32(%%rsi), %%xmm1\n\t"
                       "vfmadd231sd %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vmovsd 64(%%rsi), %%xmm2\n\t"
                       "vfmadd231sd %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 8(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vmovsd 40(%%rsi), %%xmm1\n\t"
                       "vfmadd231sd %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vmovsd 72(%%rsi), %%xmm2\n\t"
                       "vfmadd231sd %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 16(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vmovsd 48(%%rsi), %%xmm1\n\t"
                       "vfmadd231sd %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vmovsd 80(%%rsi), %%xmm2\n\t"
                       "vfmadd231sd %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 24(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vmovsd 56(%%rsi), %%xmm1\n\t"
                       "vfmadd231sd %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vmovsd 88(%%rsi), %%xmm2\n\t"
                       "vfmadd231sd %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovsd %%xmm13, 0(%%rdx)\n\t"
                       "vmovsd %%xmm14, 160(%%rdx)\n\t"
                       "vmovsd %%xmm15, 320(%%rdx)\n\t"
                       "addq $8, %%rdx\n\t"
                       "subq $248, %%rdi\n\t"
                       "cmpq $5, %%r12\n\t"
                       "jl 1b\n\t"
                       "addq $440, %%rdx\n\t"
                       "addq $96, %%rsi\n\t"
                       "subq $40, %%rdi\n\t"
                       "cmpq $3, %%r13\n\t"
                       "jl 0b\n\t"
                       "0:\n\t"
                       "addq $1, %%r13\n\t"
                       "movq $0, %%r12\n\t"
                       "1:\n\t"
                       "addq $4, %%r12\n\t"
                       "vmovupd 0(%%rdx), %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 0(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm1, %%ymm0, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 8(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm1, %%ymm0, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 16(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm1, %%ymm0, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 24(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm1, %%ymm0, %%ymm15\n\t"
                       "vmovupd %%ymm15, 0(%%rdx)\n\t"
                       "addq $32, %%rdx\n\t"
                       "subq $224, %%rdi\n\t"
                       "cmpq $4, %%r12\n\t"
                       "jl 1b\n\t"
                       "1:\n\t"
                       "addq $1, %%r12\n\t"
                       "vmovsd 0(%%rdx), %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 0(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 8(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 16(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 24(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovsd %%xmm15, 0(%%rdx)\n\t"
                       "addq $8, %%rdx\n\t"
                       "subq $248, %%rdi\n\t"
                       "cmpq $5, %%r12\n\t"
                       "jl 1b\n\t"
                       "addq $120, %%rdx\n\t"
                       "addq $32, %%rsi\n\t"
                       "subq $40, %%rdi\n\t"
                       "cmpq $4, %%r13\n\t"
                       "jl 0b\n\t"
                       : : "m"(B), "m"(A), "m"(C) : "rdi","rsi","rdx","r12","r13","r14","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15");
#else
#pragma message ("LIBXSMM KERNEL COMPILATION ERROR in: " __FILE__)
#error No kernel was compiled, lacking support for current architecture?
#endif

#ifndef NDEBUG
#ifdef _OPENMP
#pragma omp atomic
#endif
libxsmm_num_total_flops += 160;
#endif
}

void gemm_5_4_4_lduh_z(const double* A, const double* B, double* C) {
#ifdef __AVX2__
#ifdef __AVX512F__
#pragma message ("LIBXSMM KERNEL COMPILATION WARNING: compiling AVX2 code on AVX512 or newer architecture: " __FILE__)
#endif
  __asm__ __volatile__("movq %0, %%rsi\n\t"
                       "movq %1, %%rdi\n\t"
                       "movq %2, %%rdx\n\t"
                       "movq $0, %%r12\n\t"
                       "movq $0, %%r13\n\t"
                       "movq $0, %%r14\n\t"
                       "0:\n\t"
                       "addq $3, %%r13\n\t"
                       "movq $0, %%r12\n\t"
                       "1:\n\t"
                       "addq $4, %%r12\n\t"
                       "vmovupd 0(%%rdx), %%ymm13\n\t"
                       "vmovupd 640(%%rdx), %%ymm14\n\t"
                       "vmovupd 1280(%%rdx), %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 0(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm13\n\t"
                       "vbroadcastsd 32(%%rsi), %%ymm1\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm14\n\t"
                       "vbroadcastsd 64(%%rsi), %%ymm2\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 8(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm13\n\t"
                       "vbroadcastsd 40(%%rsi), %%ymm1\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm14\n\t"
                       "vbroadcastsd 72(%%rsi), %%ymm2\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 16(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm13\n\t"
                       "vbroadcastsd 48(%%rsi), %%ymm1\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm14\n\t"
                       "vbroadcastsd 80(%%rsi), %%ymm2\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 24(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm13\n\t"
                       "vbroadcastsd 56(%%rsi), %%ymm1\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm14\n\t"
                       "vbroadcastsd 88(%%rsi), %%ymm2\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovupd %%ymm13, 0(%%rdx)\n\t"
                       "vmovupd %%ymm14, 640(%%rdx)\n\t"
                       "vmovupd %%ymm15, 1280(%%rdx)\n\t"
                       "addq $32, %%rdx\n\t"
                       "subq $224, %%rdi\n\t"
                       "cmpq $4, %%r12\n\t"
                       "jl 1b\n\t"
                       "1:\n\t"
                       "addq $1, %%r12\n\t"
                       "vmovsd 0(%%rdx), %%xmm13\n\t"
                       "vmovsd 640(%%rdx), %%xmm14\n\t"
                       "vmovsd 1280(%%rdx), %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 0(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vmovsd 32(%%rsi), %%xmm1\n\t"
                       "vfmadd231sd %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vmovsd 64(%%rsi), %%xmm2\n\t"
                       "vfmadd231sd %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 8(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vmovsd 40(%%rsi), %%xmm1\n\t"
                       "vfmadd231sd %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vmovsd 72(%%rsi), %%xmm2\n\t"
                       "vfmadd231sd %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 16(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vmovsd 48(%%rsi), %%xmm1\n\t"
                       "vfmadd231sd %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vmovsd 80(%%rsi), %%xmm2\n\t"
                       "vfmadd231sd %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm3\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 24(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm3, %%xmm0, %%xmm13\n\t"
                       "vmovsd 56(%%rsi), %%xmm1\n\t"
                       "vfmadd231sd %%xmm3, %%xmm1, %%xmm14\n\t"
                       "vmovsd 88(%%rsi), %%xmm2\n\t"
                       "vfmadd231sd %%xmm3, %%xmm2, %%xmm15\n\t"
                       "vmovsd %%xmm13, 0(%%rdx)\n\t"
                       "vmovsd %%xmm14, 640(%%rdx)\n\t"
                       "vmovsd %%xmm15, 1280(%%rdx)\n\t"
                       "addq $8, %%rdx\n\t"
                       "subq $248, %%rdi\n\t"
                       "cmpq $5, %%r12\n\t"
                       "jl 1b\n\t"
                       "addq $1880, %%rdx\n\t"
                       "addq $96, %%rsi\n\t"
                       "subq $40, %%rdi\n\t"
                       "cmpq $3, %%r13\n\t"
                       "jl 0b\n\t"
                       "0:\n\t"
                       "addq $1, %%r13\n\t"
                       "movq $0, %%r12\n\t"
                       "1:\n\t"
                       "addq $4, %%r12\n\t"
                       "vmovupd 0(%%rdx), %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 0(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm1, %%ymm0, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 8(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm1, %%ymm0, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 16(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm1, %%ymm0, %%ymm15\n\t"
                       "vmovupd 0(%%rdi), %%ymm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vbroadcastsd 24(%%rsi), %%ymm0\n\t"
                       "vfmadd231pd %%ymm1, %%ymm0, %%ymm15\n\t"
                       "vmovupd %%ymm15, 0(%%rdx)\n\t"
                       "addq $32, %%rdx\n\t"
                       "subq $224, %%rdi\n\t"
                       "cmpq $4, %%r12\n\t"
                       "jl 1b\n\t"
                       "1:\n\t"
                       "addq $1, %%r12\n\t"
                       "vmovsd 0(%%rdx), %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 0(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 8(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 16(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovsd 0(%%rdi), %%xmm1\n\t"
                       "addq $64, %%rdi\n\t"
                       "vmovsd 24(%%rsi), %%xmm0\n\t"
                       "vfmadd231sd %%xmm1, %%xmm0, %%xmm15\n\t"
                       "vmovsd %%xmm15, 0(%%rdx)\n\t"
                       "addq $8, %%rdx\n\t"
                       "subq $248, %%rdi\n\t"
                       "cmpq $5, %%r12\n\t"
                       "jl 1b\n\t"
                       "addq $600, %%rdx\n\t"
                       "addq $32, %%rsi\n\t"
                       "subq $40, %%rdi\n\t"
                       "cmpq $4, %%r13\n\t"
                       "jl 0b\n\t"
                       : : "m"(B), "m"(A), "m"(C) : "rdi","rsi","rdx","r12","r13","r14","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15");
#else
#pragma message ("LIBXSMM KERNEL COMPILATION ERROR in: " __FILE__)
#error No kernel was compiled, lacking support for current architecture?
#endif

#ifndef NDEBUG
#ifdef _OPENMP
#pragma omp atomic
#endif
libxsmm_num_total_flops += 160;
#endif
}

