#!/bin/bash
# Mini build script wrapper for ExaHyPE out of tree build system.
# Autogenerated by setup-out-of-tree.sh
# @AUTOGENINFO@
set -e
cd "$(dirname "$0")"
source "oot.env"

cd $oot_codedir
cd $oot_appdir

export SKIP_TOOLKIT="${SKIP_TOOLKIT:=No}"
export CLEAN="${CLEAN:=Clean}"

time $oot_compile

# collect compilation result
verbose cp $oot_binarypath .

