#!/bin/bash
# Mini build script wrapper for ExaHyPE out of tree build system.
# Autogenerated by setup-out-of-tree.sh
# @AUTOGENINFO@
set -e
cd "$(dirname "$0")"
source "oot.env"

export SKIP_TOOLKIT="${SKIP_TOOLKIT:=No}"
export CLEAN="${CLEAN:=Clean}"

( cd $oot_codedir/$oot_appdir && time $oot_compile; )

# collect compilation result
cp $oot_binarypath .

# also collect a build log, if present
for log in "$oot_codedir/$oot_appdir/*.log"; do
	[[ -e $log ]] && cp $log .
done
