#!/bin/bash
# Mini build script wrapper for ExaHyPE out of tree build system.
# Autogenerated by setup-out-of-tree.sh
# @AUTOGENINFO@
set -e
cd "$(dirname "$0")"
source "oot.env"

rsync="rsync -r --relative --delete --exclude=.git/ --exclude=.svn/"

# assume that $oot_appdir can be quite populated with a mess
# caveats, if the variables are empty, there is --exclude=*
rsync_app_excludelist="--exclude=*.log --exclude=*.vtk --exclude=*.csv --exclude=*.mk --exclude=${oot_makesystem_prefix}* --exclude=${oot_buildprefix}*/"

echo "Build $oot_buildname: Copying files to $oot_builddir ..."

oot_codedir="$(readlink -f $oot_codedir)" # absolutize with readlink
#oot_codedir="$(pwd)/$oot_codedir/" # absolutize without readlink
cd $oot_abs_exahype # in order rsync --relative works

$rsync $oot_toolkit $oot_codedir/
$rsync $rsync_app_excludelist $oot_appdir $oot_codedir/

# before:
#cp $oot_abs_exahype/$oot_specfile @oot_codedir@/$oot_appdir/.. # the path is hacky

# after:
$rsync $oot_specfile $oot_codedir/
$rsync $oot_dependencies $oot_codedir/

echo "Finished, oot_builddir size is $(du -hs $oot_builddir | head -n1 | awk '{print $1}') in $(find $oot_builddir | wc -l) files"

