// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================
#include "exahype/plotters/Plotter.h"
namespace SRMHD{
  class IntegralsWriter;

  /**
   * Forward declaration
   */
  class MHDSolver;
}

#include "Writers/TimeSeriesReductions.h"
#include "MHDSolver.h"

class SRMHD::IntegralsWriter: public exahype::plotters::Plotter::UserOnTheFlyPostProcessing{
  public:
  static const int nVar = SRMHD::AbstractMHDSolver::NumberOfVariables;
  reductions::MultipleReductionsWriter conserved;
  reductions::MultipleReductionsWriter primitives;
  reductions::MultipleReductionsWriter errors;
  reductions::ReductionsWriter statistics;

  IntegralsWriter(MHDSolver&  solver);
  virtual ~IntegralsWriter();
  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp) override;
};
