#!/bin/bash
# usage: webmize file1.mpg file2.mov file3...
# Do not use too many files as conversion is done in parallel.

ffmpeg=$(which avconv 2>/dev/null && echo 'avconv' || which ffmpeg 2>/dev/null && echo 'ffmpeg' )
which $ffmpeg 1>/dev/null 2>/dev/null || { echo -e "Suitable ffmpeg version not found"; exit -1; }

for movie in "$@"; do

time $ffmpeg -i $movie  -acodec libvorbis -aq 5 -ac 1 -qmax 25 -threads 2 ${movie%.*}.webm &

done
wait
