#!/bin/bash
# ARGS:
#    $1 - project folder

GIT_BIN=/usr/bin/git

GIT_COMMIT_REV=`git log | head -1`
GIT_COMMIT_REV=${GIT_COMMIT_REV#commit }
GIT_COMMIT_DATE=`git log | head -3 | tail -1`
GIT_COMMIT_DATE=`echo ${GIT_COMMIT_DATE#Date\: } | xargs`

printf "/////////////////////////////////////////////////////////////////\n"            >  $1/buildinfo.h
printf "// NOTE: This file is autogenerated. Changes should be applied to\n"            >> $1/buildinfo.h
printf "// the script generate-buildinfo.sh. Recompile all depending\n"                 >> $1/buildinfo.h
printf "// make targets afterwards.\n"                                                  >> $1/buildinfo.h
printf "/////////////////////////////////////////////////////////////////\n"            >> $1/buildinfo.h
echo "#define EXAHYPE_GIT_BRANCH          "\"`${GIT_BIN} rev-parse --abbrev-ref HEAD`\" >> $1/buildinfo.h
echo "#define EXAHYPE_GIT_COMMIT_REVISION "\"${GIT_COMMIT_REV}\"                        >> $1/buildinfo.h
echo "#define EXAHYPE_GIT_COMMIT_DATE     "\"${GIT_COMMIT_DATE}\"                       >> $1/buildinfo.h
echo "#define EXAHYPE_BUILD_DATE          "\"`LC_ALL=en_US.utf8 date`\"                 >> $1/buildinfo.h
