PEANO_PATH=/home/kduru/ExaHyPE2/ExaHyPE/Code/./Peano/peano
TARCH_PATH=/home/kduru/ExaHyPE2/ExaHyPE/Code/./Peano/tarch
MULTISCALELINKEDCELL_PATH=/home/kduru/ExaHyPE2/ExaHyPE/Code/./Peano/multiscalelinkedcell
SHAREDMEMORYORACLES_PATH=/home/kduru/ExaHyPE2/ExaHyPE/Code/./Peano/sharedmemoryoracles
EXAHYPE_PATH=/home/kduru/ExaHyPE2/ExaHyPE/Code/./ExaHyPE
PROJECT_PATH=/home/kduru/ExaHyPE2/ExaHyPE/Code/./Applications/elasticwaves3d
EXECUTABLE=ExaHyPE-elasticwaves3d 



PROJECT_CFLAGS+=-DnoMultipleThreadsMayTriggerMPICalls
PROJECT_CFLAGS+=-DDim3
SHAREDMEM=TBB
DISTRIBUTEDMEM=MPI




-include /home/kduru/ExaHyPE2/ExaHyPE/Code/./ExaHyPE/Makefile




all: 
	@echo elasticwaves3d 
	@echo =================
	@echo An ExaHyPE solver
