PEANO_PATH=/home/tobias/git/ExaHyPE/Code/./Peano/peano
TARCH_PATH=/home/tobias/git/ExaHyPE/Code/./Peano/tarch
MULTISCALELINKEDCELL_PATH=/home/tobias/git/ExaHyPE/Code/./Peano/multiscalelinkedcell
EXAHYPE_PATH=/home/tobias/git/ExaHyPE/Code/./ExaHyPE
PROJECT_PATH=/home/tobias/git/ExaHyPE/Code/./Applications/trivialproject



-include /home/tobias/git/ExaHyPE/Code/./ExaHyPE/Makefile




all: 
	@echo TrivialProject 
	@echo =================
	@echo An ExaHyPE solver
