/////////////////////////////////////////////////////////////////
// NOTE: This file is autogenerated. Changes should be applied to
// the script generate-buildinfo.sh. Recompile all depending
// make targets afterwards.
/////////////////////////////////////////////////////////////////
#define EXAHYPE_GIT_BRANCH          "master"
#define EXAHYPE_GIT_COMMIT_REVISION "58f983a8a5e2cf32b33f0e78515d894c56289048"
#define EXAHYPE_GIT_COMMIT_DATE     "Wed Jul 13 21:10:03 2016 +0100"
#define EXAHYPE_BUILD_DATE          "Wed Jul 13 21:58:06 BST 2016"
