/////////////////////////////////////////////////////////////////
// NOTE: This file is autogenerated. Changes should be applied to
// the script generate-buildinfo.sh. Recompile all depending
// make targets afterwards.
/////////////////////////////////////////////////////////////////
#define EXAHYPE_GIT_BRANCH          "master"
#define EXAHYPE_GIT_COMMIT_REVISION "5935e665525b49e87d2205a7f31924d00a414a70"
#define EXAHYPE_GIT_COMMIT_DATE     "Author: WEINZIERL T <frmh84@hamilton2.dur.ac.uk>"
#define EXAHYPE_BUILD_DATE          "Thu Jul 28 15:09:34 CEST 2016"
