/////////////////////////////////////////////////////////////////
// NOTE: This file is autogenerated. Changes should be applied to
// the script generate-buildinfo.sh. Recompile all depending
// make targets afterwards.
/////////////////////////////////////////////////////////////////
#define EXAHYPE_GIT_BRANCH          "master"
#define EXAHYPE_GIT_COMMIT_REVISION "df1554b57f62e48debb8037ceba97ad568de2693"
#define EXAHYPE_GIT_COMMIT_DATE     "Thu Jul 28 15:55:46 2016 +0200"
#define EXAHYPE_BUILD_DATE          "Thu Jul 28 16:05:31 CEST 2016"
