PEANO_PATH=/home/hpc/pr63so/gu89tik2/data/ExaHyPE/Code/./Peano/peano
TARCH_PATH=/home/hpc/pr63so/gu89tik2/data/ExaHyPE/Code/./Peano/tarch
MULTISCALELINKEDCELL_PATH=/home/hpc/pr63so/gu89tik2/data/ExaHyPE/Code/./Peano/multiscalelinkedcell
SHAREDMEMORYORACLES_PATH=/home/hpc/pr63so/gu89tik2/data/ExaHyPE/Code/./Peano/sharedmemoryoracles
EXAHYPE_PATH=/home/hpc/pr63so/gu89tik2/data/ExaHyPE/Code/./ExaHyPE
PROJECT_PATH=/home/hpc/pr63so/gu89tik2/data/ExaHyPE/Code/./Applications/SRHD
EXECUTABLE=ExaHyPE-SRHD 



PROJECT_CFLAGS+=-DnoMultipleThreadsMayTriggerMPICalls
PROJECT_CFLAGS+=-DDim2


MIXEDLANG=Yes

-include /home/hpc/pr63so/gu89tik2/data/ExaHyPE/Code/./ExaHyPE/MakefileFORTRAN




all: 
	@echo SRHD 
	@echo =================
	@echo An ExaHyPE solver
