PEANO_PATH=../.././Peano/peano
TARCH_PATH=../.././Peano/tarch
MULTISCALELINKEDCELL_PATH=../.././Peano/multiscalelinkedcell
SHAREDMEMORYORACLES_PATH=../.././Peano/sharedmemoryoracles
EXAHYPE_PATH=../.././ExaHyPE
PROJECT_PATH=../.././Applications/SRHD
EXECUTABLE=ExaHyPE-SRHD 



PROJECT_CFLAGS+=-DnoMultipleThreadsMayTriggerMPICalls
PROJECT_CFLAGS+=-DDim2


MIXEDLANG=Yes

-include ../.././ExaHyPE/MakefileFORTRAN




all: 
	@echo SRHD 
	@echo =================
	@echo An ExaHyPE solver
