PEANO_PATH=/home/dominic/dev/codes/c/ExaHyPE/Code/Toolkit/./Peano/peano
TARCH_PATH=/home/dominic/dev/codes/c/ExaHyPE/Code/Toolkit/./Peano/tarch
MULTISCALELINKEDCELL_PATH=/home/dominic/dev/codes/c/ExaHyPE/Code/Toolkit/./Peano/multiscalelinkedcell
SHAREDMEMORYORACLES_PATH=/home/dominic/dev/codes/c/ExaHyPE/Code/Toolkit/./Peano/sharedmemoryoracles
EXAHYPE_PATH=/home/dominic/dev/codes/c/ExaHyPE/Code/Toolkit/./ExaHyPE
PROJECT_PATH=/home/dominic/dev/codes/c/ExaHyPE/Code/Toolkit/./Applications/SRHD
EXECUTABLE=ExaHyPE-SRHD 



PROJECT_CFLAGS+=-DnoMultipleThreadsMayTriggerMPICalls
PROJECT_CFLAGS+=-DDim2
SHAREDMEM=TBB




-include /home/dominic/dev/codes/c/ExaHyPE/Code/Toolkit/./ExaHyPE/Makefile




all: 
	@echo SRHD 
	@echo =================
	@echo An ExaHyPE solver
