// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================
#include "exahype/plotters/Plotter.h"

/* I hope these modifications are not overwritten... */
#include "GeneratedConstants.h"
#include "TimeSeriesReductions.h"
#define nVars MY_NUMBER_OF_VARIABLES

using namespace std;

class MyEulerSolver_Plotter1: public exahype::plotters::Plotter::UserOnTheFlyPostProcessing{
  TimeSeriesReductions* conserved[nVars];
  TimeSeriesReductions* primitives[nVars];
  TimeSeriesReductions* errors[nVars];
  TimeSeriesReductions* statistics;
  double time;
  
  // Auto generated:
  public:
  MyEulerSolver_Plotter1();
  virtual ~MyEulerSolver_Plotter1();
  virtual void startPlotting(double time);
  virtual void finishPlotting();
  virtual void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
  double timeStamp);
};
