/////////////////////////////////////////////////////////////////
// NOTE: This file is autogenerated. Changes should be applied to
// the script generate-buildinfo.sh. Recompile all depending
// make targets afterwards.
/////////////////////////////////////////////////////////////////
#define EXAHYPE_GIT_BRANCH          "master"
#define EXAHYPE_GIT_COMMIT_REVISION "c15d1c639fee920e073168ee30d278efb639bb1c"
#define EXAHYPE_GIT_COMMIT_DATE     "Thu Jan 21 12:08:57 2016 +0000"
#define EXAHYPE_BUILD_DATE          "Thu Jan 21 15:56:25 GMT 2016"
