/**
 * This file is part of the ExaHyPE project.
 * Copyright (c) 2016  http://exahype.eu
 * All rights reserved.
 *
 * The project has received funding from the European Union's Horizon 
 * 2020 research and innovation programme under grant agreement
 * No 671698. For copyrights and licensing, please consult the webpage.
 *
 * Released under the BSD 3 Open Source License.
 * For the full license text, see LICENSE.txt
 **/
 
/////////////////////////////////////////////////////////////////
// NOTE: This file is autogenerated. Changes should be applied to
// the script generate-buildinfo.sh. Recompile all depending
// make targets afterwards.
/////////////////////////////////////////////////////////////////
#define EXAHYPE_GIT_BRANCH "master"
#define EXAHYPE_GIT_COMMIT_REVISION "c15d1c639fee920e073168ee30d278efb639bb1c"
#define EXAHYPE_GIT_COMMIT_DATE "Thu Jan 21 12:08:57 2016 +0000"
#define EXAHYPE_BUILD_DATE "Thu Jan 21 15:56:25 GMT 2016"
