// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "DummyWriter.h"

#include <cstdlib>
#include <ctime>


Trivial::DummyWriter::DummyWriter(AdvectionSolver&  solver) {
  // @TODO Please insert your code here.
  srand(time(NULL));
}

Trivial::DummyWriter::~DummyWriter() {
}

void Trivial::DummyWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void Trivial::DummyWriter::finishPlotting() {
  // @TODO Please insert your code here.
}

void Trivial::DummyWriter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 19;
  for (int i=0; i<writtenUnknowns; i++){ 
    outputQuantities[i] = static_cast <float> (rand()) / static_cast <float> (RAND_MAX);
  }
}
