/*
 * ! This file is autogenerated and should not be modified !
 * (This file should be generated according to a config file)
 *
 * Constants.h
 */

#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#include "peano/utils/Globals.h"

#define INITIAL_GLOBAL_REFINEMENT 5
#define INITIAL_ADAPTIVE_REFINEMENT 0
#define MAXIMUM_ADAPTIVE_REFINEMENT 0

#define SIMULATION_TIME 5

#define NUMBER_OF_PDES 2

namespace exahype {
static const int numberOfVariables[NUMBER_OF_PDES] = {
    1
};
static const int order[NUMBER_OF_PDES] = {
    0
};
}

#endif /* CONSTANTS_H_ */
