// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "DifferenceWithIDWriter.h"
#include "PDE/PDE.h"
#include "InitialData.h"


GRMHD::DifferenceWithIDWriter::DifferenceWithIDWriter(GRMHDSolver_ADERDG&  solver) {
  // @TODO Please insert your code here.
}

GRMHD::DifferenceWithIDWriter::~DifferenceWithIDWriter() {
}

void GRMHD::DifferenceWithIDWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void GRMHD::DifferenceWithIDWriter::finishPlotting() {
  // @TODO Please insert your code here.
}

void GRMHD::DifferenceWithIDWriter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 19;
  
  double evolvedPrims[writtenUnknowns], exactPrims[writtenUnknowns];
  GRMHD::Cons2Prim(evolvedPrims, Q).copyFullStateVector();

  AlfenWave(x.data(),timeStamp,exactPrims);

  double *localError = outputQuantities;
  for(int i=0; i<writtenUnknowns; i++) {
    localError[i] = evolvedPrims[i] - exactPrims[i];
  }
}
