/*
 * ! This file is autogenerated and should not be modified !
 *
 * Constants.h
 */

#ifndef EXAHYPE_DG_CONSTANTS_H_
#define EXAHYPE_DG_CONSTANTS_H_

/**
 * Indexing of the neighbours of a cell in 2d.
 */
///@{
#define PEANO_2D_NEIGHBOUR_LEFT  3
#define PEANO_2D_NEIGHBOUR_RIGHT 5
#define PEANO_2D_NEIGHBOUR_FRONT 1
#define PEANO_2D_NEIGHBOUR_BACK  7
///@}

/**
 * Indexing of the neighbours of a cell in 3d.
 */
///@{
#define PEANO_3D_NEIGHBOUR_LEFT   12
#define PEANO_3D_NEIGHBOUR_RIGHT  14
#define PEANO_3D_NEIGHBOUR_FRONT  10
#define PEANO_3D_NEIGHBOUR_BACK   16
#define PEANO_3D_NEIGHBOUR_BOTTOM 4
#define PEANO_3D_NEIGHBOUR_TOP    22
///@}

/**
 * Indexing of the faces of a cell.
 */
///@{
#define EXAHYPE_FACE_LEFT   0
#define EXAHYPE_FACE_RIGHT  1
#define EXAHYPE_FACE_FRONT  2
#define EXAHYPE_FACE_BACK   3
#define EXAHYPE_FACE_BOTTOM 4
#define EXAHYPE_FACE_TOP    5
///@}

#endif /* EXAHYPE_DG_CONSTANTS_H_ */
