/////////////////////////////////////////////////////////////////
// NOTE: This file is autogenerated. Changes should be applied to
// the script generate-buildinfo.sh. Recompile all depending
// make targets afterwards.
/////////////////////////////////////////////////////////////////
#define EXAHYPE_GIT_BRANCH          "master"
#define EXAHYPE_GIT_COMMIT_REVISION "8487a2edb804e8cfa8918aeb8290613811abfe76"
#define EXAHYPE_GIT_COMMIT_DATE     "Author: tobiasweinzierl <tobias.weinzierl@durham.ac.uk>"
#define EXAHYPE_BUILD_DATE          "Wed Feb 3 16:27:37 CET 2016"
