// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================


#include "kernels/KernelCalls.h"
#include "exahype/plotters/Plotter.h"
#include "exahype/solvers/Solver.h"


#include "MyEulerSolver.h"



void kernels::initSolvers(const exahype::Parser& parser) {
  exahype::solvers::RegisteredSolvers.push_back( new Euler2d::MyEulerSolver(0) ); 
  exahype::plotters::RegisteredPlotters.push_back( new exahype::plotters::Plotter(0,0,parser)); 
}



