PEANO_PATH=/home/vvarduhn/data/ExaHyPE/Code/./Peano/peano
TARCH_PATH=/home/vvarduhn/data/ExaHyPE/Code/./Peano/tarch
MULTISCALELINKEDCELL_PATH=/home/vvarduhn/data/ExaHyPE/Code/./Peano/multiscalelinkedcell
SHAREDMEMORYORACLES_PATH=/home/vvarduhn/data/ExaHyPE/Code/./Peano/sharedmemoryoracles
EXAHYPE_PATH=/home/vvarduhn/data/ExaHyPE/Code/./ExaHyPE
PROJECT_PATH=/home/vvarduhn/data/ExaHyPE/Code/./Applications/eulerflow2d
EXECUTABLE=ExaHyPE-Euler2d 


DIM=-DDim2


-include /home/vvarduhn/data/ExaHyPE/Code/./ExaHyPE/Makefile




all: 
	@echo Euler2d 
	@echo =================
	@echo An ExaHyPE solver
