// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================
#include "exahype/plotters/Plotter.h"
namespace GRMHD{
  class IntegralsWriter;

  /**
   * Forward declaration
   */
  class GRMHDSolver;
}

#include "Writers/TimeSeriesReductions.h"
#include "GRMHDSolver.h"

class GRMHD::IntegralsWriter: public exahype::plotters::Plotter::UserOnTheFlyPostProcessing{
  public:
  static const int nVar = GRMHD::AbstractGRMHDSolver::NumberOfVariables;
  MultipleReductionsWriter conserved;
  MultipleReductionsWriter primitives;
  MultipleReductionsWriter errors;
  ReductionsWriter statistics;

  IntegralsWriter(GRMHDSolver&  solver);
  virtual ~IntegralsWriter();
  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp) override;
};
