// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================
#include "exahype/plotters/Plotter.h"
namespace Euler{
  class ComputeGlobalIntegrals;

  /**
   * Forward declaration
   */
  class MyEulerSolver;
}

/* I hope these modifications are not overwritten... */
#include "TimeSeriesReductions.h"
#include "MyEulerSolver.h"
static const int nVar = Euler::MyEulerSolver::nVar; // shortcut


class Euler::ComputeGlobalIntegrals: public exahype::plotters::Plotter::UserOnTheFlyPostProcessing{
  private:
    TimeSeriesReductions* conserved[nVar];
    TimeSeriesReductions* primitives[nVar];
    TimeSeriesReductions* errors[nVar];
    TimeSeriesReductions* statistics;
    double time;
  public:
  ComputeGlobalIntegrals(MyEulerSolver&  solver);
  virtual ~ComputeGlobalIntegrals();
  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp) override;
};
