// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "SphereIntegrals.h"


GRMHD::SphereIntegrals::SphereIntegrals() : exahype::plotters::ADERDG2UserDefined::ADERDG2UserDefined(){
  // @TODO Please insert your code here.
}


void GRMHD::SphereIntegrals::plotPatch(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch, double* u,
    double timeStamp) {
  // @TODO Please insert your code here.
}


void GRMHD::SphereIntegrals::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void GRMHD::SphereIntegrals::finishPlotting() {
  // @TODO Please insert your code here.
}
