// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================
#include "exahype/plotters/Plotter.h"
namespace Euler{
  class FirstEulerSolver_Plotter0;

  /**
   * Forward declaration
   */
  class FirstEulerSolver;
}




class Euler::FirstEulerSolver_Plotter0: public exahype::plotters::Plotter::UserOnTheFlyPostProcessing{
  public:
  FirstEulerSolver_Plotter0(FirstEulerSolver&  solver);
  virtual ~FirstEulerSolver_Plotter0();
  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp) override;
};
